### ISSUE TITLE
tarea practica de operaciones

### ISSUE THREAD

**Issue by alexis663** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-alexis663#1]
[practica operaciones.docx](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-alexis663/files/7175023/practica.operaciones.docx)

**Comment by isaireyesp1** [comment]
Potada: Falto lugar y fecha (22 puntos)

Procedimiento: Redacta de una manera fácil de entender y explicando algunas cosas fáciles de entender en el procedimiento del ejercicio, pero estos (ejercicios) son pocos, y no pusiste el objetivo de la practica ni los materiales a utilizar (15 puntos)

Figuras, ilustraciones y fotografías: No hay variedad de fotografías, ya que por cada tipo de operación son 10 ejercicios  (15 puntos)

Resultados y conclusiones: Lamentablemente no tienes resultados ni conclusiones  (15 puntos).

Total de puntos:  67 puntos / 100 puntos.
Calificación: 13.4% / 20%
Calificado por: Isai reyes peña

**Comment by josealfredo79** [comment]
Bien hecho y revisado
